apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nizar-sample-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: sample-app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nizar-sample-app-service
                port:
                  number: 80




